# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /Users/User/Icefox/mozilla-project/Icefox/mozilla-central/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
MOZ_OBJDIR=$(TOPSRCDIR)/../iphone-device-debug-ios5.1
MOZ_MAKE_FLAGS=-j6
# --enable-application=browser is used by configure (not client.mk)
# --enable-debug is used by configure (not client.mk)
# --disable-optimize is used by configure (not client.mk)
# --with-macos-sdk=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk is used by configure (not client.mk)
# --target=arm-apple-darwin10 is used by configure (not client.mk)
# --disable-printing is used by configure (not client.mk)
# --disable-plugins is used by configure (not client.mk)
# --disable-necko-wifi is used by configure (not client.mk)
# --disable-negotiateauth is used by configure (not client.mk)
# --disable-ogg is used by configure (not client.mk)
# --disable-wave is used by configure (not client.mk)
# --disable-webm is used by configure (not client.mk)
# --disable-ipc is used by configure (not client.mk)
# --disable-updater is used by configure (not client.mk)
# --disable-crashreporter is used by configure (not client.mk)
# --disable-ctypes is used by configure (not client.mk)
