/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define ACCESSIBILITY 1
#define ATTRIBUTE_ALIGNED_MAX 64
#define CROSS_COMPILE 1
#define D_INO d_ino
#define ENABLE_SYSTEM_EXTENSION_DIRS 1
#define FIREFOX_VERSION 20.0a1
#define GL_PROVIDER_ 1
#define HAVE_ARM_SIMD 1
#define HAVE_DIRENT_H 1
#define HAVE_DLADDR 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_GETOPT_H 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISATTY 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LCHOWN 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LSTAT64 1
#define HAVE_MEMMEM 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_RANDOM 1
#define HAVE_RINT 1
#define HAVE_SA_LEN 1
#define HAVE_SCONN_LEN 1
#define HAVE_SETBUF 1
#define HAVE_SIGINFO_T 1
#define HAVE_SIN6_LEN 1
#define HAVE_SIN_LEN 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STAT64 1
#define HAVE_STDINT_H 1
#define HAVE_STRERROR 1
#define HAVE_STRNDUP 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UINT 1
#define HAVE_UINT64_T 1
#define HAVE_UNISTD_H 1
#define HAVE_VISIBILITY_ATTRIBUTE 1
#define HAVE_VISIBILITY_HIDDEN_ATTRIBUTE 1
#define HAVE___CXA_DEMANGLE 1
#define IBMBIDI 1
#define JSGC_INCREMENTAL 1
#define JSGC_INCREMENTAL 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define MALLOC_H <malloc/malloc.h>
#define MOZILLA_UAVERSION "20.0"
#define MOZILLA_VERSION "20.0a1"
#define MOZILLA_VERSION_U 20.0a1
#define MOZ_APP_COMPONENT_INCLUDE "nsBrowserComponents.h"
#define MOZ_APP_UA_NAME ""
#define MOZ_APP_UA_VERSION "20.0a1"
#define MOZ_B2G_OS_NAME ""
#define MOZ_B2G_VERSION "1.0.0"
#define MOZ_BUILD_APP mobile/xul
#define MOZ_CHROME_FILE_FORMAT_JAR 1
#define MOZ_CRASHREPORTER_ENABLE_PERCENT 100
#define MOZ_CUBEB 1
#define MOZ_CUSTOM_STDINT_H "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/stdint.h"
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_DISABLE_DOMCRYPTO 1
#define MOZ_DISTRIBUTION_ID "org.mozilla"
#define MOZ_DLL_SUFFIX ".dylib"
#define MOZ_DUMP_PAINTING 1
#define MOZ_FEEDS 1
#define MOZ_FLEXBOX 1
#define MOZ_GRAPHITE 1
#define MOZ_LAYERS_HAVE_LOG 1
#define MOZ_LOGGING 1
#define MOZ_MACBUNDLE_ID org.mozilla.fennec
#define MOZ_MEDIA 1
#define MOZ_OGG 1
#define MOZ_OPUS 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_SAMPLE_TYPE_S16 1
#define MOZ_SERVICES_COMMON 1
#define MOZ_SERVICES_CRYPTO 1
#define MOZ_SERVICES_METRICS 1
#define MOZ_SERVICES_SYNC 1
#define MOZ_SOUNDTOUCH 1
#define MOZ_SPEEX_RESAMPLER 1
#define MOZ_STATIC_JS 1
#define MOZ_SYDNEYAUDIO 1
#define MOZ_TELEMETRY_DISPLAY_REV 2
#define MOZ_THUMB2 1
#define MOZ_TREE_CAIRO 1
#define MOZ_TREE_PIXMAN 1
#define MOZ_TREMOR 1
#define MOZ_UA_BUILDID ""
#define MOZ_UPDATE_CHANNEL default
#define MOZ_USER_DIR "Mozilla"
#define MOZ_USE_NATIVE_POPUP_WINDOWS 1
#define MOZ_WIDGET_UIKIT 1
#define MOZ_XUL 1
#define NO_X11 1
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define STDC_HEADERS 1
#define XP_DARWIN 1
#define XP_IOS 1
#define XP_UNIX 1
#define X_DISPLAY_MISSING 1

/* The c99 defining the limit macros (UINT32_MAX for example), says:
 * C++ implementations should define these macros only when __STDC_LIMIT_MACROS
 * is defined before <stdint.h> is included. */
#define __STDC_LIMIT_MACROS

/* Force-include hunspell_alloc_hooks.h for hunspell, so that we don't need to
 * modify it directly.
 *
 * HUNSPELL_STATIC is defined in extensions/spellcheck/hunspell/src/Makefile.in,
 * unless --enable-system-hunspell is defined.
 */
#if defined(HUNSPELL_STATIC)
#include "hunspell_alloc_hooks.h"
#endif

#endif /* _MOZILLA_CONFIG_H_ */

